SequoiaWildflowers/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^webapp/wildflowers/', include('webapp.urls')),
    url(r'^admin/', admin.site.urls),
]

webapp/urls.py
from django.conf.urls import url

from . import views

app_name = 'webapp'
urlpatterns = [
    # ex: /wildflowers/
    url(r'^$', views.index, name='wildflowers_index'),
    # ex: /wildflowers/references/
    url(r'^refernces/$', views.references, name='wildflowers_references'),
    # ex: /wildflowers/about_us?
    url(r'^about_us/$', views.about_us, name='wildflowers_about_us'),
    # ex: /wildflowers/by_common_name/
    url(r'^by_common_name/$',
        views.ByCommonNameView.as_view(),
        name='wildflowers_by_common_name'),
    # ex: /wildflowers/by_scientific_name/
    url(r'^by_scientific_name/$',
        views.ByScientificNameView.as_view(),
        name='wildflowers_by_scientific_name'),
    # ex: /wildflowers/by_family/
    url(r'^by_family/$',
        views.ByFamilyView.as_view(),
        name='wildflowers_by_family'),
    # ex: /wildflowers/by_color_range/
    url(r'^by_color_range/$',
        views.ByColorRangeView.as_view(),
        name='wildflowers_by_color_range'),
    # ex: /wildflowers/family/34/
    url(r'^family/(?P<pk>[0-9]+)/$',
        views.InFamilyView.as_view(),
        name='wildflowers_family'),
    # ex: /wildflowers/color_range/3/
    url(r'^color_range/(?P<pk>[0-9]+)/$',
        views.InColorRangeView.as_view(),
        name='wildflowers_color_range'),
    # ex: /wildflowers/detail/45/
    url(r'^detail/(?P<pk>[0-9]+)/$',
        views.PlantDetailView.as_view(),
        name='wildflowers_detail'),
]

webapp/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible
class Family(models.Model):
    scientific_name = models.CharField(max_length=100)
    icon_file_name = models.CharField(max_length=75)

    def __str__(self):
        return self.scientific_name

    def _get_formatted_common_names(self):
        common_names = self.familycommonname_set.all()
        number_of_common_names = len(common_names)
        if number_of_common_names == 0:
            return None
        elif number_of_common_names == 1:
            return common_names[0].common_name
        elif number_of_common_names == 2:
            common_name_string = common_names[0].common_name
            common_name_string += " or "
            common_name_string += common_names[1].common_name
            return common_name_string
        else:
            common_name_list = [(item.common_name) for item in common_names]
            last_common_name = common_name_list[-1]
            rest_of_common_names = common_name_list[:-1]
            common_name_string = ", ".join(rest_of_common_names)
            common_name_string += " or "
            common_name_string += last_common_name
            return common_name_string
    formatted_common_names = property(_get_formatted_common_names)


@python_2_unicode_compatible
class FamilyCommonName(models.Model):
    common_name = models.CharField(max_length=100)
    faimly = models.ForeignKey(Family, on_delete=models.CASCADE)

    def __str__(self):
        return self.common_name


@python_2_unicode_compatible
class ColorRange(models.Model):
    color_range = models.CharField(max_length=50)
    icon_file_name = models.CharField(max_length=75)

    def __str__(self):
        return self.color_range


@python_2_unicode_compatible
class Plant(models.Model):
    scientific_name = models.CharField(max_length=100)
    plant_type = models.CharField(max_length=50)
    date_added = models.DateField()
    family = models.ForeignKey(Family)
    image_colors = models.ManyToManyField(ColorRange, through='ImageInfo')

    def __str__(self):
        return self.scientific_name

    def _get_formatted_common_names(self):
        common_names = self.plantcommonname_set.all()
        number_of_common_names = len(common_names)
        if number_of_common_names == 0:
            return None
        elif number_of_common_names == 1:
            return common_names[0].common_name
        elif number_of_common_names == 2:  # need to put primary name first
            primary_name = (common_names
                            .filter(primary=True)
                            .get()
                            .common_name)
            other_name = (common_names
                          .filter(primary=False)
                          .get()
                          .common_name)
            common_name_string = primary_name
            common_name_string += " or "
            common_name_string += other_name
            return common_name_string
        else:  # need to put primary name first
            primary_name = (common_names
                            .filter(primary=True)
                            .get()
                            .common_name)
            other_names = (common_names
                           .filter(primary=False)
                           .all())
            other_name_list = [(item.common_name) for item in other_names]
            last_other_name = other_name_list[-1]
            rest_of_other_names = other_name_list[:-1]
            other_name_string = ", ".join(rest_of_other_names)
            other_name_string += " or "
            other_name_string += last_other_name
            return primary_name + ", " + other_name_string

    def _get_primary_common_name(self):
        primary_name = (self.plantcommonname_set
                            .filter(primary=True)
                            .get()
                            .common_name)
        return primary_name

    def _get_primary_image_file_name(self):
        primary_image_file_name = (self.imageinfo_set
                                   .filter(primary=True)
                                   .all())
        if len(primary_image_file_name) == 0:
            return None
        else:
            return primary_image_file_name[0].file_name

    formatted_common_names = property(_get_formatted_common_names)
    primary_common_name = property(_get_primary_common_name)
    primary_image_file_name = property(_get_primary_image_file_name)


@python_2_unicode_compatible
class PlantCommonName(models.Model):
    common_name = models.CharField(max_length=100)
    primary = models.BooleanField()
    plant = models.ForeignKey(Plant, on_delete=models.CASCADE)

    def __str__(self):
        return self.common_name


@python_2_unicode_compatible
class ImageInfo(models.Model):
    file_name = models.CharField(max_length=75)
    image_width = models.IntegerField()
    image_height = models.IntegerField()
    primary = models.BooleanField()
    plant = models.ForeignKey(Plant)
    color_range = models.ForeignKey(ColorRange)

    def __str__(self):
        return self.file_name

    def is_landscape_orientation(self):
        return True if (self.image_width >= self.image_height) else False

    def is_primary_image(self):
        return self.primary

webapp/views.py
from django.shortcuts import render, get_list_or_404
from django.views import generic
from django.db.models import Count
from .models import Family, FamilyCommonName, ImageInfo
from .models import ColorRange, Plant, PlantCommonName

# Create your views here.


class ByCommonNameView(generic.ListView):
    template_name = 'webapp/by_common_name.html'
    context_object_name = 'plant_common_name_list'

    def get_queryset(self):
        """Return all plant common names"""
        return (PlantCommonName.objects.all()
                .filter(plant__imageinfo__primary=True)
                .order_by('common_name'))


class ByScientificNameView(generic.ListView):
    template_name = 'webapp/by_scientific_name.html'
    context_object_name = 'plant_scientific_name_list'

    def get_queryset(self):
        """Return all plant scientific names"""
        return Plant.objects.all().order_by('scientific_name')


class ByFamilyView(generic.ListView):
    template_name = 'webapp/by_family.html'
    context_object_name = 'family_list'

    def get_queryset(self):
        """Return all plant families"""
        return Family.objects.all().order_by('scientific_name')


class ByColorRangeView(generic.ListView):
    template_name = 'webapp/by_color_range.html'
    context_object_name = 'color_range_list'

    def get_queryset(self):
        """Return all plant color_ranges"""
        return ColorRange.objects.all().order_by('color_range')


class InFamilyView(generic.ListView):
    template_name = 'webapp/in_family.html'
    context_object_name = 'plants_in_family_list'

    def get_queryset(self):
        """Return all plants in a family"""
        f_id = self.kwargs['pk']
        q_set = Plant.objects.filter(
            family_id=f_id).order_by('scientific_name')
        plant_list = get_list_or_404(q_set)
        return plant_list


class InColorRangeView(generic.ListView):
    template_name = 'webapp/in_color_range.html'
    context_object_name = 'plants_in_color_range_list'

    def get_queryset(self):
        """Return all plants in a color_ranges"""
        cr_id = self.kwargs['pk']
        q_set = (Plant.objects
                 .filter(imageinfo__color_range_id=cr_id)
                 .order_by('scientific_name')
                 .annotate(Count('scientific_name')))
        plant_list = get_list_or_404(q_set)
        print plant_list[0]
        return plant_list


class PlantDetailView(generic.DetailView):
    model = Plant
    template_name = 'webapp/plant_detail.html'


def index(request):
    return render(request, 'webapp/index.html')


def references(request):
    return render(request, 'webapp/references.html')


def about_us(request):
    return render(request, 'webapp/about_us.html')

webapp/templates/webapp/about_us.html
{% extends 'webapp/base.html' %}
{% block plug_in_content %}
{% load staticfiles %}
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    <h1>About Us</h1>
    <div class="AboutUs">  
      <h2>Jake</h2>
      <img src="{% static 'webapp/images/us/jake_1558.jpg' %}" width="150" height="150" class="LeftImg" />
      <p>Jacob is a native Californian. He has been camping and backpacking in the Sierras since before he could walk. He is a physicist and is also interested in geology and astronomy. He enjoys snowboarding in the winter and camping and hiking the rest of the year.</p>
    </div>
    
    <div class="AboutUs">
      <h2>Nastia</h2>
      <img src="{% static 'webapp/images/us/nastia_3748.jpg' %}" width="150" height="150" class="LeftImg" />
      <p>Nastia grew up in Russia, and moved to California in 1995. She is a physicist and mathematician. She enjoys camping and hiking as well as drawing, tatting, graphic and web design.</p>
    </div>

    <div class="AboutUs">
      <h2><a href="#">Leo</a></h2>
      <a href="#"><img src="{% static 'webapp/images/us/leo_0142.jpg' %}" width="150" height="150" class="LeftImg" /></a>
      <p>Leo is our assistant. He helps us to identify species by eating them and then throwing them up in the middle of the living room. Obviously, he is the most important part of the team.</p>
    </div>

    <div class="AboutUs">
      <h2><a href="#">Monty & Phoenix</a></h2>
      <a href="#"><img src="{% static 'webapp/images/us/kittens_3614b.jpg' %}" width="150" height="150" class="LeftImg" /></a>
      <p>Monty & Phoenix are our computer technicians. They help by pressing keys we never thought of pressing (usually DELETE) and attacking the mouse pointer. When it's time for a break, they snuggle next to the warm laptop and take a nap.</p>
    </div>

  </div>
  <div class="col-md-2"></div>
</div>
{% endblock %}

webapp/templates/webapp/base.html
{% load staticfiles %}
<html>
  <head>
    <title>Sequoia Wildflowers</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'webapp/style.css' %}" />
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="{% static 'webapp/bootstrap.min.js' %}"></script>
    
  </head>

  <body role="document">

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'webapp:wildflowers_index' %}">Sequoia Wildflowers</a>
        </div><!--/.nav-header -->
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">

	    <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Wildflowers <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'webapp:wildflowers_by_common_name' %}">
		    Common Name
		</a></li>
                <li><a href="{% url 'webapp:wildflowers_by_scientific_name' %}">
		    Scientific Name
		</a></li>
                <li><a href="{% url 'webapp:wildflowers_by_family' %}">
		    By Family
		</a></li>
                <li><a href="{% url 'webapp:wildflowers_by_color_range' %}">
		    By Color
		</a></li>
              </ul>
            </li>
          </ul>

	  <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'webapp:wildflowers_references' %}">References</a></li>
            <li><a href="{% url 'webapp:wildflowers_about_us' %}">About Us</a></li>
          </ul>

        </div><!--/.nav-collapse -->
      </div><!--/.container -->
    </nav>

    <div class="container main-container">
      <!-- Main jumbotron for a primary marketing message or call to action -->

      <div class="row stripe-background">
	<div class="col-md-12">
	  <div class="jumbotron">
	  </div>
	</div>
      </div><!-- /.row -->
      
      <div class="row">

	{% block plug_in_content %}
	{% endblock %}

      </div>

    </div> <!-- /container -->
  </body>
</html>

webapp/templates/webapp/by_color_range.html
{% extends 'webapp/base.html' %}
{% block plug_in_content %}
{% load staticfiles %}
{% if color_range_list %}
<div class="row">
  <h1>Wildflowers by Color</h1>
</div>
<div class="row">
  <div class="col-sm-3 col-md-3 col-lg-3"></div>
  <div class="col-sm-6 col-md-6 col-lg-6">
    <div class="row">
      {% for color_range in color_range_list %}
      <div class="col-sm-6 col-md-6 col-lg-6">
	<div class="media" style="margin-left: 10px;">
	  <div class="media-left media-middle">
	    <a href="{% url 'webapp:wildflowers_color_range' color_range.id %}">
	      <img class="media-object" src="{% static 'webapp/images/icons/color/' %}{{color_range.icon_file_name}}" alt="{{ color_range.icon_file_name }}" width="100" height="100">
	    </a>
	  </div>
	  <div class="media-body media-left media-middle">
	    <h4 class="media-heading">
	      <a href="{% url 'webapp:wildflowers_color_range' color_range.id %}">
		<span style="font-size: 1.5em;">{{ color_range.color_range }}</span>
	      </a>
	    </h4>
	  </div>
	</div>
      </div><!-- /.col-md-4 col-lg-4-->
      {% endfor %}
    </div>
  </div>
  <div class="col-sm-3 col-md-3 col-lg-3"></div>
</div><!-- /.row -->
{% else %}
<p>No color ranges are available.</p>
{% endif %}
{% endblock %}

webapp/templates/webapp/by_common_name.html
{% extends 'webapp/base.html' %}

{% block plug_in_content %}
{% load staticfiles %}
{% if plant_common_name_list %}
<div class="row">
  <h1>Wildflowers by Common Name</h1>
</div>
<div class="row">
  {% for plant_common_name in plant_common_name_list %}
  <div class="col-md-6 col-lg-4">
    <h3>
      <a href="{% url 'webapp:wildflowers_detail' plant_common_name.plant_id %}">
	{{ plant_common_name }}
      </a>
    </h3>
    <div class="ImageBox">
      <a href="{% url 'webapp:wildflowers_detail' plant_common_name.plant_id %}">
	<span></span>

	<img height="243" alt="{{ plant_common_name.plant.primary_image_file_name }}" src="{% static 'webapp/images/thumbnails/' %}{{plant_common_name.plant.primary_image_file_name}}" width="324" />
      </a>
    </div>
    <dl>
      <dt>
	<a href="{% url 'webapp:wildflowers_detail' plant_common_name.plant_id %}">
	  {{ plant_common_name.plant.scientific_name }}
	</a>
      </dt>
      <dd>
	<a href="{% url 'webapp:wildflowers_family' plant_common_name.plant.family.id %}">
	  {{ plant_common_name.plant.family.scientific_name }}
	</a>
      </dd>
    </dl>
  </div><!-- /.col-md-6 col-lg-4-->
  {% endfor %}
</div><!-- /.row -->
{% else %}
<p>No plant common names are available.</p>
{% endif %}
{% endblock %}

webapp/templates/webapp/by_family.html
{% extends 'webapp/base.html' %}
{% block plug_in_content %}
{% load staticfiles %}
{% if family_list %}
<div class="row">
  <h1>Wildflowers by Family</h1>
</div>
<div class="row">
  <div class="col-sm-1 col-md-1"></div>
  <div class="col-sm-10 col-md-10 col-lg-12">
    <div class="row">
      {% for family in family_list %}
      <div class="col-sm-12 col-md-6 col-lg-4">
	
	<div class="media" style="margin-left: 10px;">
	  <div class="media-left media-middle">
	    <a href="{% url 'webapp:wildflowers_family' family.id %}">
	      <img class="media-object" src="{% static 'webapp/images/icons/family/' %}{{family.icon_file_name}}" alt="{{ family.icon_file_name }}" width="80" height="80">
	    </a>
	  </div>
	  <div class="media-body media-middle">
	    <dl>
	      <dt class="media-heading">
		<a href="{% url 'webapp:wildflowers_family' family.id %}">
		  {{ family.scientific_name }}
		</a>
	      </dt>
	      <dd>
		<a href="{% url 'webapp:wildflowers_family' family.id %}">
		  {{ family.formatted_common_names }}<span> Family</span>
		</a>
	    </dd>
	    </dl>
	  </div>
	</div>
      </div><!-- /.col-md-6 col-lg-4-->
      {% endfor %}
    </div>
  </div>
  <div class="col-sm-1 col-md-1"></div>
</div>
{% else %}
<p>No families are available.</p>
{% endif %}
{% endblock %}



	

webapp/templates/webapp/by_scientific_name.html
{% extends 'webapp/base.html' %}
{% block plug_in_content %}
{% load staticfiles %}
{% if plant_scientific_name_list %}
<div class="row">
  <h1>Wildflowers by Scientific Name</h1>
</div>
<div class="row">
  {% for plant_scientific_name in plant_scientific_name_list %}
  <div class="col-md-6 col-lg-4">
    <h3>
      <a href="{% url 'webapp:wildflowers_detail' plant_scientific_name.id %}">
	{{ plant_scientific_name }}
      </a>
    </h3>
    <div class="ImageBox">
      <a href="{% url 'webapp:wildflowers_detail' plant_scientific_name.id %}">
	<span></span>
	<img height="243" alt="{{ plant_scientific_name.primary_image_file_name }}" src="{% static 'webapp/images/thumbnails/' %}{{plant_scientific_name.primary_image_file_name}}" width="324" />
      </a>
    </div>
    <dl>
      <dt>
	<a href="{% url 'webapp:wildflowers_detail' plant_scientific_name.id %}">
	{{ plant_scientific_name.primary_common_name }}
	</a>
      </dt>
      <dd>
	<a href="{% url 'webapp:wildflowers_family' plant_scientific_name.family_id %}">
	  {{ plant_scientific_name.family.scientific_name }}
	</a>
      </dd>
    </dl>
  </div><!-- /.col-md-6 col-lg-4-->
  {% endfor %}
</div><!-- /.row -->
{% else %}
<p>No plant scientific names are available.</p>
{% endif %}
{% endblock %}

webapp/templates/webapp/in_color_range.html
{% extends 'webapp/base.html' %}
{% block plug_in_content %}
{% load staticfiles %}
{% if plants_in_color_range_list %}
<div class="row">
  <h1>Wildflowers</h1>
</div>

<div class="row">
  {% for plant in plants_in_color_range_list %}
  <div class="col-md-6 col-lg-4">

    <h3>
      <a href="{% url 'webapp:wildflowers_detail' plant.id %}">
	{{ plant.primary_common_name }}
      </a>
    </h3>

    <div class="ImageBox">
      <a href="{% url 'webapp:wildflowers_detail' plant.id %}">
	<span></span>
	<img height="243" alt="{{ plant.primary_image_file_name }}" src="{% static 'webapp/images/thumbnails/' %}{{plant.primary_image_file_name}}" width="324" />
      </a>
    </div>
    <dl>
      <dt>
	<a href="{% url 'webapp:wildflowers_detail' plant.id %}">
	  <p>{{ plant }}</p>
	</a>
      </dt>
      <dd>
	<a href="{% url 'webapp:wildflowers_family' plant.family_id %}">
	  {{ plant.family.scientific_name }}
	</a>
      </dd>
    </dl>
  </div><!-- /.col-md-6 col-lg-4-->
  {% endfor %}
</div><!-- /.row -->
{% else %}
<p>No plants are available.</p>
{% endif %}
{% endblock %}

webapp/templates/webapp/in_family.html
{% extends 'webapp/base.html' %}
{% block plug_in_content %}
{% load staticfiles %}
{% if plants_in_family_list %}
<div class="row">
  <h1>{{plants_in_family_list.0.family.scientific_name}}</h1>
  <h4>{{plants_in_family_list.0.family.formatted_common_names}} Family</h4>
</div>

<div class="row">
  {% for plant in plants_in_family_list %}
  <div class="col-md-6 col-lg-4">

    <h3>
      <a href="{% url 'webapp:wildflowers_detail' plant.id %}">
	{{ plant.primary_common_name }}
      </a>
    </h3>

    <div class="ImageBox">
      <a href="{% url 'webapp:wildflowers_detail' plant.id %}">
	<span></span>
	<img height="243" alt="{{ plant.primary_image_file_name }}" src="{% static 'webapp/images/thumbnails/' %}{{plant.primary_image_file_name}}" width="324" />
      </a>
    </div>
    <dl>
      <dt>
	<a href="{% url 'webapp:wildflowers_detail' plant.id %}">
	  <p>{{ plant }}</p>
	</a>
      </dt>
      <dd>
	<a href="{% url 'webapp:wildflowers_family' plant.family_id %}">
	  {{ plant_scientific_name.family.scientific_name }}
	</a>
      </dd>
    </dl>
  </div><!-- /.col-md-6 col-lg-4-->
  {% endfor %}
</div><!-- /.row -->

{% else %}
<p>No plants are available.</p>
{% endif %}
{% endblock %}

webapp/templates/webapp/index.html
{% extends 'webapp/base.html' %}
{% block plug_in_content %}
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    <div class="row"><h1>Welcome</h1></div>

    <div class="row">
      <div class="paddedText">
      <p>We like to visit Sequoia and Kings Canyon National Parks several times a year, usually from late spring until early fall.  We like to visit other national parks as well, especially those in California, but find ourselves returning to Sequoia and Kings Canyon over and over.  In many ways, we enjoy these parks much more than their more popular Sierra Nevada cousin, Yosemite National Park.  Everyone should certainly experience Yosemite at least once in their lives, but Sequoia and Kings Canyon are equally beautiful and rich with life, but without the huge crowds, without the need to make reservations months in advance and without tiny campsites packed together like sardines.  Sequoia and Kings Canyon feel more like wilderness than civilization.  Today, these parks are much like the Yosemite of decades ago.</p>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6">
      <a href="#">
    	<img src="http://placehold.it/324x243" width="324" height="243" alt="" /></a>
      </div>
      <div class="col-md-6">
	We enjoy going on a lot of hikes throughout the parks, and we are always curious about the plants and animals around us.  We are not botanists, just hobbyists.  Over the years we have acquired a lot of pictures and a lot of guidebooks, and decided to share our accumulated knowledge through this website.
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
<p>The site is primarily dedicated to identification of wildflowers found in Sequoia and Kings Canyon National Parks, but we have added a few other sections.  You can choose to view the wildflowers organized by common name, scientific name, family, or color.  We also have few <a href="#">Mystery Plants</a> we have not been able to identify.  If you can help us identify any of these, or would just like to comment on the site, please <a href="#">contact us</a>! Many of the species contained here can be found elsewhere in the Sierras, Central Valley, Bay Area or beyond.  Though we have only included species here that we found in or around Sequoia or Kings Canyon, we hope this guide can be helpful for those visiting Yosemite or other parks or even help you identify flowers in your neighborhood!</p>
      </div>
      <div class="col-md-6">
<a href="#">
	<img src="http://placehold.it/324x486" alt="" width="324" height="486" /></a>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
      <a href="#">
    	<img src="http://placehold.it/324x486" width="324" height="486" alt="" /></a>
      </div>
      <div class="col-md-6">
<p>We have also toyed with 3D photography for a couple of years and our photos are getting better and better. Part of the motivation for building a 3D camera was to try to capture the grandeur of areas like the Sierra Nevada that can sometimes be awe-inspiring in person, but lose something when photographed.  You can see some sample images and read more about 3D photography in the <a href="#">3D Images</a> section.</p> 

<p>In addition, we have provided a <a href="{% url 'webapp:wildflowers_references' %}">Reference Section</a> containing books and websites we have found to be helpful.<!--If you enjoy this website and would like to learn more, please buy one of these books or other items you find here through our links. These are the products we use from the places we purchased them.  It will not cost you anything extra; just offer a little support to help us continue to develop this site. --> </p>      </div>
    </div>
  </div><!-- /.col-md-8 -->
  <div class="col-md-2"></div>
</div><!-- /.row -->



{% endblock %}

webapp/templates/webapp/plant_detail.html
{% extends 'webapp/base.html' %}
{% block plug_in_content %}
{% load staticfiles %}
{% if plant %}
<div class="row">
  <h1>{{plant.primary_common_name}}</h1>
</div>
<div class="row">
  <div class="col-sm-2 col-md-2 col-lg-2"></div>
  <div class="col-sm-8 col-md-8 col-lg-8">
    <div class="row">
      <div class="col-sm-12 col-md-12 col-lg-12">

	Plant Species: {{ plant.scientific_name }}</br>
	Commonly known as: {{ plant.formatted_common_names }}</br>
	<a href="{% url 'webapp:wildflowers_family' plant.family_id %}">
	  Plant Family: {{ plant.family.scientific_name }}</a></br>
	Family commonly know as: {{ plant.family.formatted_common_names }} Family</br>

	{% for image_info in plant.imageinfo_set.all %}
	<div class="col-sm-6 col-md-6 col-lg-6">
	  <a href="#">
	    <img src="{% static 'webapp/images/thumbnails/' %}{{ image_info.file_name }}" alt="{{ image_info.file_name }}">
	  </a>
	</div><!-- /.col-sm-6 col-md-6 col-lg-6 -->
	{% endfor %}
      </div><!-- /.col-sm-12 col-md-12 col-lg-12 -->
    </div>
  </div>
</div>
<div class="col-sm-2 col-md-2 col-lg-2"></div>
</div><!-- /.row -->
{% else %}
<p>No plants are available.</p>
{% endif %}
{% endblock %}